### ISSUE TITLE
Add vertical margin to inline <code> 

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#292]
Currently, inline code blocks overlap vertically, if they appear in consecutive lines:

![Screenshot 2019-09-24 at 19 24 17](https://user-images.githubusercontent.com/168390/65535147-275edb00-df01-11e9-8fbb-c3f0c9e589db.png)

Current CSS rule:
```css
.theme-default-content code {
    padding: 0.25rem 0.5rem;
    margin: 0;
}
```

My proposal is to move some of the vertical padding to the vertical margin:
```css
.theme-default-content code {
    padding: 0.05rem 0.5rem;
    margin: 0.2rem 0;
}
```

Result:

![Screenshot 2019-09-24 at 19 27 48](https://user-images.githubusercontent.com/168390/65535297-6ab94980-df01-11e9-9b37-7433b795b8d4.png)
