### ISSUE TITLE
Set code::after.content to None

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#293]
The following code block
<pre>
```python
topic = 'notify'+'.'+notification['subject']
```
</pre>
is rendered with an additional newline, e.g. 

![Screenshot 2019-09-24 at 19 46 34](https://user-images.githubusercontent.com/168390/65536590-09df4080-df04-11e9-9a82-b5e325e49577.png)

This is due to the `code::after.content` being set to empty string:
```css
code::before, code::after {
    content: '';
}
```

I propose to set the content to `None`:
```css
code::before, code::after {
    content: None;
}
```
Result:

![Screenshot 2019-09-24 at 19 47 18](https://user-images.githubusercontent.com/168390/65536647-24191e80-df04-11e9-8e12-ed3c7a11cab7.png)
